name: image build
on:
    workflow_call:
      inputs:
        DOCKER_IMAGE:
          type: string
          required: true
    workflow_dispatch:
      inputs:
        DOCKER_IMAGE:
          required: true

jobs:
    build:
      runs-on: ubuntu-latest
      permissions:
        contents: read
        packages: write
        id-token: write
      steps:
        - name: init
          uses: actions/checkout@v3
          with:
            fetch-depth: 1
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v2

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        
        - id: string
          uses: ASzc/change-string-case-action@v5
          with:
            string: ${{ inputs.DOCKER_IMAGE }}
        
        - id: platforms
          run:
            echo platforms=`cat ${{ inputs.DOCKER_IMAGE }}/platforms || echo "linux/amd64,linux/arm64"` >> $GITHUB_OUTPUT

        - name: Publish to Registry
          uses: docker/build-push-action@v4
          with:
            push: true
            context: ${{ inputs.DOCKER_IMAGE }}
            tags:  ghcr.io/tsic404/${{ steps.string.outputs.lowercase }}:latest
            platforms: ${{steps.platforms.outputs.platforms}}
